const godNames = [
    "Buk",
    "Azazyl",
    "Desmug",
    "Zypheros",
    "Morgath",
    "Elyndra",
    "Vorlun",
    "Nyxara",
    "Kalindur",
    "Beazilbub",
    "Lillithae",
    "Xal'Thor",
    "Morvathis",
    "Thal'Zeen",
    "Orcus",
    "Zerathul",
    "Gorath",
    "Velshara",
    "Draxxis",
    "Erebus",
    "Nerathis",
    "Zal'Korath",
    "Malzahar",
    "Sylthara",
    "Vexorath",
    "Kharzun",
    "Lorthal",
    "Zylaria",
    "Morvex",
    "Xerathul",
    "Thal'Zor",
    "Vorathis",
    "Nyxorus",
    "Kalindor",
    "Beazilthor",
    "Lillithor",
    "Xal'Zeen",
    "Morvathul",
    "Thal'Korath",
    "Orcuthis",
    "Zerathis",
    "Gorathul",
    "Velsharath",
    "Draxxor",
    "Erebor",
    "Nerathor",
    "Zal'Korul",
    "Malzathis",
    "Syltharath",
    "Vexorul",
    "Kharzoth",
    "Lorthul",
    "Jeff"
];

const godTitles = [
    "Devourer",
    "Eternal Watch",
    "The Bringer",
    "The Abyssal",
    "The One",
    "The Beguiler",
    "The Silent",
    "Sleeping One",
    "Blood God",
    "God of Pleasure",
    "The Wyrm King",
    "Faceless One",
    "Lord of Flies",
    "Mistress of Maggots",
    "Forsaken",
    "The Rot",
    "The Unknowing",
    "Idiot God",
    "The Blind",
    "Broken",
    "Laughing God",
    "Lich King",
    "Folk Lord",
    "Harvest God",
    "Flesh Lover",
    "The Dead One",
    "Keeper of Lies",
    "All Seeing",
    "The Quiet One",
    "The Wandering",
    "The Pale Lord",
    "Bone Collector",
    "The Veiled",
    "The Hollow",
    "Skin King",
    "Lord of Jeffs",
    "The Whisperer",
    "The Nameless",
    "The Forgotten",
    "The Cursed",
    "The Eternal",
    "The Dreadful",
    "The Insatiable",
    "The Unseen",
    "The Corruptor",
    "Twisted Nightmare",
    "Harbringer",
    "God of the Sands",
    "The Veinbinder",
    "Frost Lord",
    "Black Mass",
    "Goat Father",
    "The Unholy",
    "All-Consuming",
    "Polka Fiend"
];

const godDomains = [
    "Death",
    "Decay",
    "Insanity",
    "Shadows",
    "Chaos",
    "Trickery",
    "Skulls",
    "Disease",
    "Secrets",
    "Haversting",
    "Reaping",
    "Murder",
    "The End of the World",
    "Jeff",
    "Madness",
    "Darkness",
    "Sin",
    "Flesh",
    "Bones",
    "Blood",
    "Plague",
    "Nightmares",
    "Whispers",
    "Knowledge",
    "Dreams",
    "Fear",
    "Despair",
    "Corruption",
    "Doom",
    "Mutation",
    "Wizardy",
    "Time",
    "Lust",
    "Gluttony",
    "Pride",
    "Greed",
    "Envy",
    "Wrath",
    "Sloth",
    "Antagonism",
    "Betrayal",
    "Written Lies",
    "Forgotten Truths",
    "Eternal Night",
    "Endless Hunger",
    "Unending Suffering",
    "Hate of the Righteous",
    "Revenge against the Living",
    "Destruction of Order",
    "Beasts",
    "Anarchy"
];

const godTraits = [
    "Followers must offer a sacrifice of blood weekly",
    "Temples are built underground or in dark places",
    "Worshippers wear masks to honor the god's nature",
    "Worshippers must chant the unknowable",
    "Followers abstain from sunlight",
    "Temples are adorned with bones and skulls",
    "Worshippers engage in ritualistic dance",
    "Worshippers must refer to the god as 'My Leige'",
    "Followers must eat the flesh of spiders",
    "Worshippers tattoo all of their skin",
    "Followers must fast for three days before rituals",
    "Worshippers must wear skull codpieces",
    "Followers must howl at the moon during rituals",
    "Followers must drink blood mead",
    "Worshippers must eat living maggots",
    "Followers must carve symbols into their flesh",
    "Worshippers must wear robes made of human skin",
    "Followers must sleep in coffins",
    "All worshippers must cut off at least one finger",
    "All followers must be named Jeff",
    "Worshippers must carry bones as talismans",
    "Followers must paint their faces like skulls",
    "Worshippers must wear chains during rituals",
    "Followers must consume fungal flesh",
    "Worshippers must wear gloves made of sheep guts",
    "Worshippers must wear pumpkins",
    "Followers must wear goat skulls",
    "Worshippers must wear cloaks of bells",
    "Followers must all be clean shaven",
];

const godImages = [
    "Images/gods/NPCS__15.png",
    "Images/gods/NPCS__16.png",
    "Images/gods/NPCS__28.png",
    "Images/gods/NPCS__31.png",
    "Images/gods/NPCS__38.png",
    "Images/gods/NPCS__40.png",
    "Images/gods/NPCS__41.png",
    "Images/gods/NPCS__48.png",
    "Images/gods/NPCS__53.png",
    "Images/gods/Zealots_1.png",
    "Images/gods/Zealots_3.png",
    "Images/gods/Zealots_5.png",
    "Images/gods/Zealots_17.png",
    "Images/gods/Zealots_31.png",
    "Images/gods/Zealots_34.png"
];


function generateGod() {
    const gname = godNames[Math.floor(Math.random() * godNames.length)];
    const title = godTitles[Math.floor(Math.random() * godTitles.length)];
    const domain = godDomains[Math.floor(Math.random() * godDomains.length)];
    const traits = godTraits[Math.floor(Math.random() * godTraits.length)];
    let godImg = godImages[Math.floor(Math.random() * godImages.length)];

    document.getElementById("god_result").innerHTML =
        `<strong>${gname} ${title}</strong><br>Domain: ${domains}<br>Trait: ${traits}`;
    document.getElementById("god_Image").innerHTML =
        `<img src="${godImg}" alt="Picture of a God">`;
}