"use strict";

const godNames = [
    "Buk",
    "Azazyl",
    "Desmug",
    "Zypheros",
    "Morgath",
    "Elyndra",
    "Vorlun",
    "Nyxara",
    "Kalindur",
    "Beazilbub",
    "Lillithae",
    "Xal'Thor",
    "Morvathis",
    "Thal'Zeen",
    "Orcus",
    "Zerathul",
    "Gorath",
    "Velshara",
    "Draxxis",
    "Erebus",
    "Nerathis",
    "Zal'Korath",
    "Malzahar",
    "Sylthara",
    "Vexorath",
    "Kharzun",
    "Lorthal",
    "Zylaria",
    "Morvex",
    "Xerathul",
    "Thal'Zor",
    "Vorathis",
    "Nyxorus",
    "Kalindor",
    "Beazilthor",
    "Lillithor",
    "Xal'Zeen",
    "Morvathul",
    "Thal'Korath",
    "Orcuthis",
    "Zerathis",
    "Gorathul",
    "Velsharath",
    "Draxxor",
    "Erebor",
    "Nerathor",
    "Zal'Korul",
    "Malzathis",
    "Syltharath",
    "Vexorul",
    "Kharzoth",
    "Lorthul",
    "Jeff",
    "Gorkath",
    "Morkath",
    "Zulthu",
    "Xerxes",
    "Muuk Buuk",
    "Throng",
    "Gororath"
];

const godTitles = [
    "Devourer",
    "Form Shifter",
    "Debt Collector",
    "Eternal Watch",
    "Gambler",
    "The Bringer",
    "The Abyssal",
    "The One",
    "The Beguiler",
    "The Silent",
    "Sleeping One",
    "Blood God",
    "God of Pleasure",
    "The Wyrm King",
    "Faceless One",
    "Lord of Flies",
    "Mistress of Maggots",
    "Forsaken",
    "The Rot",
    "The Unknowing",
    "Idiot God",
    "Defiler",
    "The Blind",
    "Broken",
    "Laughing God",
    "Lich King",
    "Folk Lord",
    "Harvest God",
    "Flesh Lover",
    "The Dead One",
    "Keeper of Lies",
    "All Seeing",
    "The Quiet One",
    "The Wandering",
    "The Pale Lord",
    "Bone Collector",
    "The Veiled",
    "The Hollow",
    "Skin King",
    "Lord of Jeffs",
    "The Whisperer",
    "The Nameless",
    "The Forgotten",
    "The Cursed",
    "The Eternal",
    "The Dreadful",
    "The Insatiable",
    "The Unseen",
    "The Corruptor",
    "Twisted Nightmare",
    "Master of None",
    "Harbringer",
    "God of the Sands",
    "The Veinbinder",
    "Frost Lord",
    "Black Mass",
    "Goat Father",
    "The Unholy",
    "All-Consuming",
    "Polka Fiend",
    "The Troll",
    "Mountain King",
    "Consuming One",
    "The Gate Keeper",
    "The Towering",
    "The Uncaring",
    "Dreaming God",
    "Lord of Gnashing Teeth",
    "Clay Idol",
    "The Maw",
    "The Idol",
    "Idle God",
    "Cow God",
    "The Great Eye",
    "Golden Calf",
    "Bull Lord",
    "Goat Lord",
    "The Horned"
];

const godDomains = [
    "Death",
    "Decay",
    "Insanity",
    "Gambling",
    "Violence",
    "Debtors",
    "Fungi",
    "Shadows",
    "Chaos",
    "Trickery",
    "Skulls",
    "Disease",
    "Secrets",
    "Haversting",
    "Reaping",
    "Murder",
    "The End of the World",
    "Jeff",
    "Madness",
    "Darkness",
    "Sin",
    "Flesh",
    "Bones",
    "Blood",
    "Plague",
    "Nightmares",
    "Whispers",
    "Knowledge",
    "Dreams",
    "Fear",
    "Despair",
    "Corruption",
    "Doom",
    "Mutation",
    "Wizardy",
    "Time",
    "Lust",
    "Gluttony",
    "Pride",
    "Greed",
    "Envy",
    "Wrath",
    "Sloth",
    "Antagonism",
    "Betrayal",
    "Written Lies",
    "Forgotten Truths",
    "Eternal Night",
    "Endless Hunger",
    "Unending Suffering",
    "Hate of the Righteous",
    "Revenge against the Living",
    "Destruction of Order",
    "Beasts",
    "Anarchy"
];

const godTraits = [
    "Melting Flesh",
    "Whispering Voice",
    "Multiple Eyes",
    "Tentacles",
    "Skeleton",
    "Shadow Skin",
    "Blood Dripping",
    "Fungal Growths",
    "Insect Swarm Cloud",
    "Cloaked in Shadows",
    "Glowing Runes",
    "Rotting Odor",
    "Bone Protrusions",
    "Smoke Breath",
    "Icy Breath",
    "Quick to Anger",
    "Liar",
    "Contractual",
    "Blood Thristy",
    "Grandiose Wings",
    "Canabalistic",
    "Profaine",
    "Gift Giving",
    "ALways Wears Red",
    "Always Eats Before Sunrise",
    "Never Sleeps",
    "Never Steps Foot in Sunlight",
    "Never Steps Foot on Holy Ground",
    "Collects Souls in the Form of Pennys",
    "Gambles for Worshippers' Lives",
    "Speaks in Tongues",
    "Only Refers to Others as 'Jeff'",
    "Has a Laugh that Can Shatter Glass",
    "Has Eyes Everywhere",
];

const godImages = [
    "Images/gods/NPCS__15.png",
    "Images/gods/NPCS__16.png",
    "Images/gods/NPCS__24.png",
    "Images/gods/NPCS__28.png",
    "Images/gods/NPCS__30.png",
    "Images/gods/NPCS__31.png",
    "Images/gods/NPCS__38.png",
    "Images/gods/NPCS__40.png",
    "Images/gods/NPCS__41.png",
    "Images/gods/NPCS__47.png",
    "Images/gods/NPCS__48.png",
    "Images/gods/NPCS__53.png",
    "Images/gods/Zealots_1.png",
    "Images/gods/Zealots_3.png",
    "Images/gods/Zealots_5.png",
    "Images/gods/Zealots_11.png",
    "Images/gods/Zealots_16.png",
    "Images/gods/Zealots_17.png",
    "Images/gods/Zealots_31.png",
    "Images/gods/Zealots_34.png",
    "Images/gods/NPCS__37.png",
    "Images/gods/NPCS__49.png",
    "Images/gods/NPCS__52.png"
];

const godCommands = [
    "Followers must offer a sacrifice of blood weekly",
    "Temples are built underground or in dark places",
    "Worshippers wear masks to honor the god's nature",
    "Worshippers must chant the unknowable",
    "Followers abstain from sunlight",
    "Temples are adorned with bones and skulls",
    "Worshippers engage in ritualistic dance",
    "Worshippers must refer to the god as 'My Leige'",
    "Followers must eat the flesh of spiders",
    "Worshippers tattoo all of their skin",
    "Followers must fast for three days before rituals",
    "Worshippers must wear skull codpieces",
    "Followers must howl at the moon during rituals",
    "Followers must drink blood mead",
    "Worshippers must eat living maggots",
    "Followers must carve symbols into their flesh",
    "Worshippers must wear robes made of human skin",
    "Followers must sleep in coffins",
    "All worshippers must cut off at least one finger",
    "All followers must be named Jeff",
    "Worshippers must carry bones as talismans",
    "Followers must paint their faces like skulls",
    "Worshippers must wear chains during rituals",
    "Followers must consume fungal flesh",
    "Worshippers must wear gloves made of sheep guts",
    "Worshippers must wear pumpkins",
    "Followers must wear goat skulls",
    "Worshippers must wear cloaks of bells",
    "Followers must all be clean shaven",
    "Followers must mate with pigs",
    "Followers must slit their wrists",
    "Followers must drink hallucinogens",
    "Worshippers must be naked during rituals",
    "Worshippers must cover themselves in ash",
    "Worshippers must carve their eyes out",
    "Followers must be baptised in urine",
    "Worshippers must wear spiked collars",
    "Followers must not eat of anything but human meat",
    "Followers must not sleep for more than two hours at a time",
    "Followers must not pass through doorways",
    "Followers must not speak the name of this god",
    "Worshippers must not partake in transportation",
    "Worshippers must not eat the flesh of cows",
    "Worshippers must not eat the flesh of goats",
    "Worshippers must not eat the flesh of pigs",
    "Followers must eat the flesh of Jeffs",
    "Follwers must urinate on holy ground",
    "Followers must only eat the flesh of pigs",
    "Worshippers must only eat the flesh of goats",
    "Followers must only eat the flesh of cows"
];

const godPowers = [
    "Gaze of Stone",
    "Acid Touch",
    "Cult Hive Mind",
    "Necromancy",
    "Pyromancy",
    "Golemancy",
    "Soul Reaping",
    "Bone Shaping",
    "Eternal Call",
    "Plague Spreading",
    "Mystical Disease",
    "Parasitic Control",
    "Mutations",
    "Strom Calling",
    "Shapeshifting",
    "Invunerable to Mortal Weapons",
    "Immortality",
    "Soul Consumption",
    "Insanity",
    "Divine Gifts",
    "Jeff Control",
    "Psychic Manipulation",
    "Otherworldly Screams",
    "Beast Summoning",
    "Blood Bending",
    "Flesh Puppeteering",
];

function getRandom(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function generateGod() {
    const gname = getRandom(godNames);
    const title = getRandom(godTitles);
    const domain = getRandom(godDomains);
    const trait = getRandom(godTraits);
    const command = getRandom(godCommands);
    const power = getRandom(godPowers);
    const godImg = getRandom(godImages);

    // Build clickable elements
    document.getElementById("god_result").innerHTML = `
        <strong id="godName">${gname}</strong> 
        <span id="godTitle">${title}</span><br>
        Domain: <span id="godDomain">${domain}</span><br>
        Trait: <span id="godTrait">${trait}</span><br>
        Power: <span id="godPower">${power}</span><br>
        Commandment: <span id="godCommand">${command}</span>
    `;

    document.getElementById("god_Image").innerHTML =
        `<img id="godImg" src="${godImg}" alt="Picture of a God">`;

    // Click handlers for rerolling each part
    document.getElementById("godName").onclick = () => {
        document.getElementById("godName").textContent = getRandom(godNames);
    };
    document.getElementById("godTitle").onclick = () => {
        document.getElementById("godTitle").textContent = getRandom(godTitles);
    };
    document.getElementById("godDomain").onclick = () => {
        document.getElementById("godDomain").textContent = getRandom(godDomains);
    };
    document.getElementById("godTrait").onclick = () => {
        document.getElementById("godTrait").textContent = getRandom(godTraits);
    };
    document.getElementById("godPower").onclick = () => {
        document.getElementById("godPower").textContent = getRandom(godPowers);
    };
    document.getElementById("godCommand").onclick = () => {
        document.getElementById("godCommand").textContent = getRandom(godCommands);
    };
    document.getElementById("godImg").onclick = () => {
        document.getElementById("godImg").src = getRandom(godImages);
    };
}
